name: "ontrack-github-ingestion-validation-data"
description: "GitHub Action used to inject data into validations in Ontrack."
inputs:
  # Misc
  logging:
    description: 'If set to true, logs additional information on the console'
    required: false
    default: 'false'
  # Target project
  owner:
    description: 'Name of the repository owner to target'
    required: false
    default: ''
  repository:
    description: 'Name of the repository to target'
    required: false
    default: ''
  # Target build
  build-name:
    description: 'Name of the build to target'
    required: false
    default: ''
  build-label:
    description: 'Release property (label) of the build to target'
    required: false
    default: ''
  # Validation
  validation:
    description: 'Name of the validation stamp to create. Defaults to the current step name.'
    required: false
    default: ''
  # Validation data options
  validation-data:
    description: 'Object describing the validation data'
    required: false
    default: ''
  test-summary-validation-data:
    description: 'Results of tests'
    required: false
    default: ''
  metrics-validation-data:
    description: 'Metrics'
    required: false
    default: ''
  file-validation-data-type:
    description: 'Type of file containing the validation data'
    required: false
    default: ''
  file-validation-data-path:
    description: 'Path to the file containing the validation data'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
