general:
  validationJobPrefix: false
workflows:
  filter:
    includes: build
runs:
  enabled: true
validations:
  - name: build-run
    description: Complete CI build has run
    image: nemerosa/ontrack-ingestion-assets/validations/build.png
promotions:
  - name: BRONZE
    description: Build OK
    image: nemerosa/ontrack-ingestion-assets/promotions/bronze.png
    validations:
      - build-run
tagging:
  strategies:
    - type: latest
casc:
  project:
    casc:
      properties:
        buildLinkDisplayProperty:
          useLabel: true
