name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ONTRACK_URL: "${{ secrets.ONTRACK_URL }}"
      ONTRACK_TOKEN: "${{ secrets.ONTRACK_TOKEN }}"
    steps:

      - uses: actions/checkout@v3
        id: checkout

      - run: npm ci
        id: build

      - run: npm run lint
        id: lint

      - run: npm run test
        id: test

      - id: tagging
        if: github.ref == 'refs/heads/main'
        run: |
          git tag main-test-${{ github.run_number }}
          git push origin main-test-${{ github.run_number }}

      - id: raw-validation-data-test
        name: raw-validation-data-test
        uses: ./
        with:
          logging: true
          validation-status: PASSED
          validation-data: |-
            type: "net.nemerosa.ontrack.extension.general.validation.TestSummaryValidationDataType"
            data:
              passed: 15
              skipped: 8
              failed: 5

      - id: raw-validation-data-test-by-name
        name: raw-validation-data-test-by-name
        uses: ./
        with:
          logging: true
          build-name: "units-test-${{ github.run_number }}"
          validation-status: PASSED
          test-summary-validation-data: |-
            passed: 15
            skipped: 8
            failed: 5

      - id: raw-validation-data-test-by-label
        name: raw-validation-data-test-by-label
        uses: ./
        with:
          logging: true
          build-label: "main-test-${{ github.run_number }}"
          validation-status: PASSED
          test-summary-validation-data: |-
            passed: 23
            skipped: 15
            failed: 8

      - id: specific-validation-data-test
        name: specific-validation-data-test
        uses: ./
        with:
          validation-status: PASSED
          test-summary-validation-data: |-
            passed: 15
            skipped: 8
            failed: 5

      - id: file-validation-data-test
        name: file-validation-data-test
        uses: ./
        with:
          logging: true
          validation-status: PASSED
          file-validation-data-type: junit
          file-validation-data-path: test/junit

      - id: raw-validation-data-metrics
        name: raw-validation-data-metrics
        uses: ./
        with:
          validation-status: PASSED
          validation-data: |-
            type: "net.nemerosa.ontrack.extension.general.validation.MetricsValidationDataType"
            data:
              metrics:
                - name: position
                  value: 2.1
                - name: speed
                  value: 15.0
                - name: acceleration
                  value: 7.1

      - id: specific-validation-data-metrics
        name: specific-validation-data-metrics
        uses: ./
        with:
          validation-status: PASSED
          metrics-validation-data: |-
            position: 2.1
            speed: 15.0
            acceleration: 7.1

      - id: file-validation-data-metrics
        name: file-validation-data-metrics
        uses: ./
        with:
          validation-status: PASSED
          file-validation-data-type: metrics
          file-validation-data-path: test/metrics.yaml

      - id: filling-typed-unit-tests
        uses: ./
        with:
          validation: typed-unit-tests
          test-summary-validation-data: |-
            passed: 1
            skipped: 1
            failed: 0

      - id: typed-metrics
        uses: ./
        with:
          metrics-validation-data: |-
            position: 10.0
            speed: 15.0
            acceleration: -0.2
