name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint
      - run: npm run test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: raw-validation-data-test
        name: raw-validation-data-test
        uses: ./
        with:
          validation-data: |-
            type: "net.nemerosa.ontrack.extension.general.validation.TestSummaryValidationDataType"
            data:
              passed: 15
              skipped: 8
              failed: 5
      - id: specific-validation-data-test
        name: specific-validation-data-test
        uses: ./
        with:
          test-summary-validation-data: |-
            passed: 15
            skipped: 8
            failed: 5
      - id: file-validation-data-test
        name: file-validation-data-test
        uses: ./
        with:
          file-validation-data-type: junit
          file-validation-data-path: test/junit

      - id: raw-validation-data-metrics
        name: raw-validation-data-metrics
        uses: ./
        with:
          validation-data: |-
            type: "net.nemerosa.ontrack.extension.general.validation.MetricsValidationDataType"
            data:
              metrics:
                position: 2.1
                speed: 15.0
                acceleration: 7.1
      - id: specific-validation-data-metrics
        name: specific-validation-data-metrics
        uses: ./
        with:
          metrics-validation-data: |-
            position: 2.1
            speed: 15.0
            acceleration: 7.1
      - id: file-validation-data-metrics
        name: file-validation-data-metrics
        uses: ./
        with:
          file-validation-data-type: metrics
          file-validation-data-path: test/metrics.yaml
